### ISSUE TITLE
[UI/UX] Rebrand Galoy Pay to Flash Pay

### ISSUE THREAD

**Issue by islandbitcoin** [lnflash/flash-pay#1]
Rebrand entire galoy-pay web frontend to be branded and themed for Flash.

-  Replace all blink images with flash images
-  Replace all galoy text (Blink, BBW, Bitcoin Beach Wallet, Galoy, etc) to Flash
-  Modify color scheme to match flash color scheme

Bounty Available ⚡⚡⚡

Staging backend: https://development.flashapp.me:8080/graphql
Staging websocket: wss://development.flashapp.me:8080/graphqlws

**Comment by ecurrencyhodler** [comment]
Bounty has been [posted](https://community.sphinx.chat/bounty/553)!
