### ISSUE TITLE
DNSSEC: Lightning Address wallet failures

### ISSUE THREAD

**Issue by brh28** [lnflash/flash-pay#20]
Unable to receive funds to from set of wallets providers (e.g Phoenix, bitvora) to our Lightning address. Phoenix provides the error: "This address is hosted on an unsecure DNS. DNSSEC must be enabled."

**Comment by islandbitcoin** [comment]
I already enabled this for islandbitcoin.com - I will do the same for flashapp.me

**Comment by islandbitcoin** [comment]
@brh28  for testing, can you send a test payment from phoenix to dread@islandbitcoin.com please?

**Comment by brh28** [comment]
From Flash or from external wallet?

**Comment by islandbitcoin** [comment]
DNSSEC enabled and DS record updated on registrar.

Please test again

**Comment by islandbitcoin** [comment]
Closing as resolved
