### ISSUE TITLE
Resolve build checks failures

### ISSUE THREAD

**Issue by brh28** [lnflash/flash-pay#4]
Resolve the following:

`make check-code` produces vulnerabilities in @babel/traverse. might just require a package update

**Comment by islandbitcoin** [comment]
yea. package update did it for me
`yarn upgrade`

**Comment by islandbitcoin** [comment]
I also had to manually fix a few files with prettier. you can see my changes in https://github.com/lnflash/flash-pay/pull/7

**Comment by brh28** [comment]
The `audit` and `check-code` are successful on the most recent build. We good to close this? @islandbitcoin
